### ISSUE TITLE
mozjpeg fails to install correctly and thus jpegs come out as zero bytes

### ISSUE THREAD

**Issue by gkatsev** [vseventer/hexo-imagemin#1]
On OSX with node 4, `imagemin-mozjpeg` doesn't install correctly.
It still tries to run images through it and thus jpegs fail. I noticed this with the banner.jpg on the default hexo landscape theme.

Apparently, it's an OSX/imagemin issue: https://github.com/imagemin/imagemin-mozjpeg/issues/11

**Comment by vseventer** [comment]
As this is an issue with a dependency, better open an issue there - looks like there are some useful replies in [imagemin/imagemin-mozjpeg#11](https://github.com/imagemin/imagemin-mozjpeg/issues/11) to resolve this.

**Comment by gkatsev** [comment]
Yeah, at first I wasn't sure what it was and this is more for informational purposes. It seems like it's being solved already.
